import { mkdtemp, readFile, rm } from "node:fs/promises";
import { join } from "node:path";
import { tmpdir } from "node:os";
import { afterEach, describe, expect, it } from "vitest";
import { MockProvider } from "@flint/providers";
import { FileStorage } from "@flint/storage";
import { FlintOrchestrator } from "./index.js";
import type { JudgeRequest, PlanRequest, PlanResult, ProviderAdapter, RunResult, StepRunRequest, ToolPermissionDecision, ToolPermissionRequest } from "@flint/core-types";

let tempDirs: string[] = [];

async function createOrchestrator(maxConcurrentTasks = 1) {
  const dir = await mkdtemp(join(tmpdir(), "flint-test-"));
  tempDirs.push(dir);
  const storage = new FileStorage(join(dir, "state.json"));
  await storage.init();
  return new FlintOrchestrator({
    storage,
    providers: [new MockProvider()],
    workspaceId: "workspace",
    maxConcurrentTasks
  });
}

async function createOrchestratorInWorkspace(
  workspaceId: string,
  options: {
    allowFileWrites?: boolean;
    allowTerminalCommands?: boolean;
    requestToolPermission?: (request: ToolPermissionRequest) => Promise<ToolPermissionDecision>;
  } = {}
) {
  const dir = await mkdtemp(join(tmpdir(), "flint-state-test-"));
  tempDirs.push(dir);
  const storage = new FileStorage(join(dir, "state.json"));
  await storage.init();
  return new FlintOrchestrator({
    storage,
    providers: [new MockProvider()],
    workspaceId,
    maxConcurrentTasks: 1,
    ...options
  });
}

async function waitFor(assertion: () => Promise<boolean>, timeoutMs = 5000): Promise<void> {
  const start = Date.now();
  while (Date.now() - start < timeoutMs) {
    if (await assertion()) {
      return;
    }
    await new Promise((resolve) => setTimeout(resolve, 20));
  }
  throw new Error("Timed out waiting for assertion");
}

afterEach(async () => {
  await Promise.all(tempDirs.map((dir) => rm(dir, { recursive: true, force: true })));
  tempDirs = [];
});

describe("FlintOrchestrator", () => {
  it("runs a task through planning, steps, judging to completed", async () => {
    const orchestrator = await createOrchestrator();
    const task = await orchestrator.createTask({
      title: "Complete task",
      prompt: "Do the thing",
      workspaceId: "workspace"
    });

    await waitFor(async () => (await orchestrator.getTask(task.id)).task.status === "completed");
    const detail = await orchestrator.getTask(task.id);
    expect(detail.evaluation?.verdict).toBe("pass");
    expect(detail.task.result?.format).toBe("markdown");
    expect(detail.task.result?.content).toContain("## Step Results");
    expect(detail.task.plan?.steps).toHaveLength(3);
    expect(detail.task.acceptanceCriteria?.length).toBeGreaterThan(0);
    expect(detail.evaluation?.criteriaResults?.length).toBeGreaterThan(0);
    expect(detail.task.plan?.steps.every((step) => step.status === "completed")).toBe(true);
    expect(detail.task.taskGraph?.nodes).toHaveLength(3);
    expect(detail.task.attempts?.[0].status).toBe("completed");
    expect(detail.events.map((event) => event.type)).toContain("task.plan_created");
    expect(detail.events.map((event) => event.type).filter((type) => type === "task.step_started")).toHaveLength(3);
    expect(detail.events.map((event) => event.type).filter((type) => type === "task.step_completed")).toHaveLength(3);
    expect(detail.events.map((event) => event.type)).toContain("task.judging");
    expect(detail.events.map((event) => event.type)).toContain("task.result_created");
    expect(detail.events.map((event) => event.type)).toContain("judge.completed");
    expect(detail.events.map((event) => event.type)).toContain("task.criteria_created");
    expect(detail.events.map((event) => event.type)).toContain("reflection.created");
  });

  it("executes workspace file tools and records evidence when file writes are allowed", async () => {
    const workspace = await mkdtemp(join(tmpdir(), "flint-workspace-test-"));
    tempDirs.push(workspace);
    const orchestrator = await createOrchestratorInWorkspace(workspace, { allowFileWrites: true });
    const task = await orchestrator.createTask({
      title: "Write file",
      prompt: "[[tool-write]] create a file",
      workspaceId: workspace
    });

    await waitFor(async () => (await orchestrator.getTask(task.id)).task.status === "completed");
    const detail = await orchestrator.getTask(task.id);
    expect(await readFile(join(workspace, "flint-tool-output.txt"), "utf8")).toContain("Generated by Flint");
    expect(detail.task.evidence?.some((item) => item.toolName === "writeFile" && item.status === "succeeded")).toBe(true);
    expect(detail.task.result?.content).toContain("## Evidence");
    // Verify workspace snapshot was collected before planning
    expect(detail.task.evidence?.some((item) => item.toolName === "listFiles")).toBe(true);
    expect(detail.events.map((event) => event.type)).toContain("task.workspace_snapshot");
  });

  it("records policy evidence and requires review when file writes are disabled", async () => {
    const workspace = await mkdtemp(join(tmpdir(), "flint-workspace-test-"));
    tempDirs.push(workspace);
    const orchestrator = await createOrchestratorInWorkspace(workspace);
    const task = await orchestrator.createTask({
      title: "Denied write",
      prompt: "[[tool-write]] create a file",
      workspaceId: workspace
    });

    await waitFor(async () => (await orchestrator.getTask(task.id)).task.status === "review_required");
    const detail = await orchestrator.getTask(task.id);
    expect(detail.task.evidence?.some((item) => item.status === "denied")).toBe(true);
    expect(detail.evaluation?.criteriaResults?.some((item) => item.status === "unknown")).toBe(true);
  });

  it("uses canonical verdict so deterministic failures override a lenient judge pass", async () => {
    const workspace = await mkdtemp(join(tmpdir(), "flint-workspace-test-"));
    tempDirs.push(workspace);
    const dir = await mkdtemp(join(tmpdir(), "flint-state-test-"));
    tempDirs.push(dir);
    const storage = new FileStorage(join(dir, "state.json"));
    await storage.init();
    const orchestrator = new FlintOrchestrator({
      storage,
      providers: [new LenientJudgeProvider()],
      workspaceId: workspace,
      maxConcurrentTasks: 1
    });
    const task = await orchestrator.createTask({
      title: "Denied but judge passes",
      prompt: "[[tool-write]] create a file",
      workspaceId: workspace,
      permissionMode: "read_only"
    });

    await waitFor(async () => (await orchestrator.getTask(task.id)).task.status === "review_required");
    const detail = await orchestrator.getTask(task.id);
    expect(detail.evaluation?.verdict).toBe("review_required");
    expect(detail.evaluation?.overallVerdict).toBe("review_required");
    expect(detail.evaluation?.findings.join("\n")).toContain("Canonical verdict review_required overrode judge verdict pass");
  });

  it("stores and loads reflections for similar future tasks", async () => {
    const orchestrator = await createOrchestrator();
    const first = await orchestrator.createTask({
      title: "First docs task",
      prompt: "Explain documentation architecture",
      workspaceId: "workspace"
    });
    await waitFor(async () => (await orchestrator.getTask(first.id)).task.status === "completed");

    const second = await orchestrator.createTask({
      title: "Second docs task",
      prompt: "Explain documentation architecture again",
      workspaceId: "workspace"
    });
    await waitFor(async () => (await orchestrator.getTask(second.id)).task.status === "completed");
    const detail = await orchestrator.getTask(second.id);
    expect(detail.events.map((event) => event.type)).toContain("reflection.loaded");
  });

  it("asks for task tool permission and executes after approval", async () => {
    const workspace = await mkdtemp(join(tmpdir(), "flint-workspace-test-"));
    tempDirs.push(workspace);
    const requests: ToolPermissionRequest[] = [];
    const orchestrator = await createOrchestratorInWorkspace(workspace, {
      requestToolPermission: async (request) => {
        requests.push(request);
        return "approved_once";
      }
    });
    const task = await orchestrator.createTask({
      title: "Approve write",
      prompt: "[[tool-write]] create a file",
      workspaceId: workspace
    });

    await waitFor(async () => (await orchestrator.getTask(task.id)).task.status === "completed");
    const detail = await orchestrator.getTask(task.id);
    expect(requests).toHaveLength(3);
    expect(requests[0].scope).toBe("file_write");
    expect(await readFile(join(workspace, "flint-tool-output.txt"), "utf8")).toContain("Generated by Flint");
    expect(detail.events.map((event) => event.type)).toContain("permission.requested");
    expect(detail.events.map((event) => event.type)).toContain("permission.approved");
  });

  it("remembers approved task scope for later tool calls", async () => {
    const workspace = await mkdtemp(join(tmpdir(), "flint-workspace-test-"));
    tempDirs.push(workspace);
    let requestCount = 0;
    const orchestrator = await createOrchestratorInWorkspace(workspace, {
      requestToolPermission: async () => {
        requestCount += 1;
        return "approved_for_task";
      }
    });
    const task = await orchestrator.createTask({
      title: "Approve writes once for task",
      prompt: "[[tool-write]] create a file",
      workspaceId: workspace
    });

    await waitFor(async () => (await orchestrator.getTask(task.id)).task.status === "completed");
    const detail = await orchestrator.getTask(task.id);
    expect(requestCount).toBe(1);
    expect(detail.task.permissions?.grantedScopes).toContain("file_write");
  });

  it("does not ask for approval when a task has full access", async () => {
    const workspace = await mkdtemp(join(tmpdir(), "flint-workspace-test-"));
    tempDirs.push(workspace);
    let requestCount = 0;
    const orchestrator = await createOrchestratorInWorkspace(workspace, {
      requestToolPermission: async () => {
        requestCount += 1;
        return "denied";
      }
    });
    const task = await orchestrator.createTask({
      title: "Full access write",
      prompt: "[[tool-write]] create a file",
      workspaceId: workspace,
      permissionMode: "full_access"
    });

    await waitFor(async () => (await orchestrator.getTask(task.id)).task.status === "completed");
    expect(requestCount).toBe(0);
    expect(await readFile(join(workspace, "flint-tool-output.txt"), "utf8")).toContain("Generated by Flint");
  });

  it("automatically validates Python artifacts when terminal permission is available", async () => {
    const workspace = await mkdtemp(join(tmpdir(), "flint-workspace-test-"));
    tempDirs.push(workspace);
    const orchestrator = await createOrchestratorInWorkspace(workspace);
    const task = await orchestrator.createTask({
      title: "Python artifact",
      prompt: "[[tool-python]] create and run a python file",
      workspaceId: workspace,
      permissionMode: "full_access"
    });

    await waitFor(async () => (await orchestrator.getTask(task.id)).task.status === "completed", 3000);
    const detail = await orchestrator.getTask(task.id);
    expect(detail.task.evidence?.some((item) => item.toolName === "environmentCheck")).toBe(true);
    expect(detail.task.evidence?.some((item) => item.toolName === "runTests" && item.status === "succeeded" && item.command?.includes("flint_artifact.py"))).toBe(true);
    expect(detail.events.map((event) => event.type)).toContain("artifact_validation.completed");
    expect(detail.events.filter((event) => event.type === "artifact_validation.completed" && event.payload.toolName === "runTests")).toHaveLength(1);
    expect(detail.events.map((event) => event.type)).toContain("artifact_validation.skipped_no_changes");
  });

  it("denies write tools without prompting for read-only tasks", async () => {
    const workspace = await mkdtemp(join(tmpdir(), "flint-workspace-test-"));
    tempDirs.push(workspace);
    let requestCount = 0;
    const orchestrator = await createOrchestratorInWorkspace(workspace, {
      requestToolPermission: async () => {
        requestCount += 1;
        return "approved_once";
      }
    });
    const task = await orchestrator.createTask({
      title: "Read-only write",
      prompt: "[[tool-write]] create a file",
      workspaceId: workspace,
      permissionMode: "read_only"
    });

    await waitFor(async () => (await orchestrator.getTask(task.id)).task.status === "review_required");
    const detail = await orchestrator.getTask(task.id);
    expect(requestCount).toBe(0);
    expect(detail.task.evidence?.some((item) => item.status === "denied" && item.toolName === "policy")).toBe(true);
  });

  it("revises the plan according to iteration policy when LLM evaluation requires more work", async () => {
    const orchestrator = await createOrchestrator();
    const task = await orchestrator.createTask({
      title: "Needs revision",
      prompt: "[[judge-review]] improve the result",
      workspaceId: "workspace"
    });

    await waitFor(async () => (await orchestrator.getTask(task.id)).task.status === "review_required");
    const detail = await orchestrator.getTask(task.id);
    expect(detail.task.evaluationAttempts).toBe(3);
    expect(detail.task.result?.revision).toBe(3);
    expect(detail.task.plan?.steps.length).toBeGreaterThan(3);
    expect(detail.evaluation?.verdict).toBe("review_required");
    expect(detail.task.progressLedger?.scoreHistory).toHaveLength(3);
    expect(detail.task.attempts).toHaveLength(3);
    expect(detail.events.map((event) => event.type).filter((type) => type === "task.plan_revised")).toHaveLength(2);
    expect(detail.events.map((event) => event.type)).toContain("iteration.decision");
  });

  it("uses local evaluation fallback when provider judge fails", async () => {
    const workspace = await mkdtemp(join(tmpdir(), "flint-workspace-test-"));
    tempDirs.push(workspace);
    const dir = await mkdtemp(join(tmpdir(), "flint-state-test-"));
    tempDirs.push(dir);
    const storage = new FileStorage(join(dir, "state.json"));
    await storage.init();
    const provider = new JudgeFailingProvider();
    const orchestrator = new FlintOrchestrator({
      storage,
      providers: [provider],
      workspaceId: workspace,
      maxConcurrentTasks: 1,
      defaultPermissionMode: "full_access"
    });
    const task = await orchestrator.createTask({
      title: "Judge fallback",
      prompt: "[[tool-write]] create a file",
      workspaceId: workspace,
      permissionMode: "full_access"
    });

    await waitFor(async () => (await orchestrator.getTask(task.id)).task.status === "completed");
    const detail = await orchestrator.getTask(task.id);
    expect(detail.evaluation?.verdict).toBe("pass");
    expect(detail.evaluation?.findings.join("\n")).toContain("LLM judge failed");
    expect(detail.events.map((event) => event.type)).toContain("judge.provider_failed");
  });

  it("keeps an agent reserved while waiting for user input", async () => {
    const orchestrator = await createOrchestrator(2);
    const task = await orchestrator.createTask({
      title: "Needs input",
      prompt: "[[ask]] choose an option",
      workspaceId: "workspace"
    });

    await waitFor(async () => (await orchestrator.getTask(task.id)).task.status === "waiting_user");
    expect(orchestrator.getAgents()[0].status).toBe("waiting_user");
    expect((await orchestrator.getTask(task.id)).task.currentStepId).toBeTruthy();
  });

  it("resumes a waiting task after user input", async () => {
    const orchestrator = await createOrchestrator();
    const task = await orchestrator.createTask({
      title: "Needs input",
      prompt: "[[ask]] choose an option",
      workspaceId: "workspace"
    });

    await waitFor(async () => (await orchestrator.getTask(task.id)).task.status === "waiting_user");
    await orchestrator.respondToUserInput(task.id, "Use option A");
    await waitFor(async () => (await orchestrator.getTask(task.id)).task.status === "completed");
  });

  it("deletes a queued task", async () => {
    const orchestrator = await createOrchestrator(1);
    const task = await orchestrator.createTask({
      title: "Delete me",
      prompt: "Do work",
      workspaceId: "other-workspace"
    });

    await orchestrator.deleteTask(task.id);
    await expect(orchestrator.getTask(task.id)).rejects.toThrow("Task not found");
  });

  it("deletes a waiting task and releases the reserved agent", async () => {
    const orchestrator = await createOrchestrator(2);
    const task = await orchestrator.createTask({
      title: "Delete waiting",
      prompt: "[[ask]] choose an option",
      workspaceId: "workspace"
    });

    await waitFor(async () => (await orchestrator.getTask(task.id)).task.status === "waiting_user");
    await orchestrator.deleteTask(task.id);

    await expect(orchestrator.getTask(task.id)).rejects.toThrow("Task not found");
    expect(orchestrator.getAgents().some((agent) => agent.taskId === task.id)).toBe(false);
    expect(orchestrator.getAgents()[0].status).toBe("idle");
  });

  it("uses fallback plan when provider planning fails", async () => {
    const dir = await mkdtemp(join(tmpdir(), "flint-test-"));
    tempDirs.push(dir);
    const storage = new FileStorage(join(dir, "state.json"));
    await storage.init();
    const provider = new FailingPlanProvider();
    const orchestrator = new FlintOrchestrator({
      storage,
      providers: [provider],
      workspaceId: "workspace",
      maxConcurrentTasks: 1
    });
    const task = await orchestrator.createTask({ title: "Fallback", prompt: "Do work", workspaceId: "workspace" });

    await waitFor(async () => (await orchestrator.getTask(task.id)).task.status === "completed");
    const detail = await orchestrator.getTask(task.id);
    expect(detail.task.plan?.summary).toBe("Fallback execution plan");
    expect(detail.events.map((event) => event.type)).toContain("task.plan_fallback");
  });

  it("marks the task failed when a step fails", async () => {
    const orchestrator = await createOrchestrator();
    const task = await orchestrator.createTask({
      title: "Failing step",
      prompt: "[[step-fail]]",
      workspaceId: "workspace"
    });

    await waitFor(async () => (await orchestrator.getTask(task.id)).task.status === "failed");
    const detail = await orchestrator.getTask(task.id);
    expect(detail.task.plan?.steps.some((step) => step.status === "failed")).toBe(true);
    expect(detail.events.map((event) => event.type)).toContain("task.step_failed");
  });
});

class FailingPlanProvider extends MockProvider implements ProviderAdapter {
  override async plan(_request: PlanRequest): Promise<PlanResult> {
    throw new Error("bad plan");
  }

  override async runStep(request: StepRunRequest) {
    return {
      summary: `Completed fallback step ${request.step.index}`,
      rawOutput: "ok"
    };
  }
}

class JudgeFailingProvider extends MockProvider implements ProviderAdapter {
  override async runStep(request: StepRunRequest): Promise<RunResult> {
    if (request.step.index === 1) {
      return {
        summary: "Created evidence for local judge fallback.",
        rawOutput: "tool write",
        toolCalls: [
          {
            name: "writeFile",
            input: { path: "judge-fallback.txt", content: "ok\n" }
          }
        ]
      };
    }
    return {
      summary: `Completed step ${request.step.index}`,
      rawOutput: "ok"
    };
  }

  override async judge(_request: JudgeRequest) {
    throw new Error("fetch failed");
  }
}

class LenientJudgeProvider extends MockProvider implements ProviderAdapter {
  override async judge(request: JudgeRequest) {
    const result = await super.judge({ ...request, evidence: [] });
    return {
      ...result,
      verdict: "pass" as const,
      findings: [],
      criteriaResults: request.acceptanceCriteria?.map((criteria) => ({
        criteriaId: criteria.id,
        statement: criteria.statement,
        status: "pass" as const,
        rationale: "Lenient judge ignored deterministic evidence.",
        evidenceRefs: []
      })) ?? []
    };
  }
}
